### ISSUE TITLE
The enum constant file needs a corresponding case label in this enum switch on Encrypt.OPT

### ISSUE THREAD

**Issue by miranos** [fhissen/CrococryptFile#3]
Hi,

I am gettings 3 Warning when compiling from Eclipse:
```
Description	Resource	Path	Location	Type
The enum constant provider needs a corresponding case label in this enum switch on Encrypt.OPT	Encrypt.java	/Crococrypt/main/org/crococryptfile/ui/gui/pages	line 135	Java Problem
The enum constant folder needs a corresponding case label in this enum switch on Decrypt.OPT	Decrypt.java	/Crococrypt/main/org/crococryptfile/ui/gui/pages	line 88	Java Problem
The enum constant file needs a corresponding case label in this enum switch on Encrypt.OPT	Encrypt.java	/Crococrypt/main/org/crococryptfile/ui/gui/pages	line 135	Java Problem
```

I generated the JAR file but it's doesnt work, when i launch it, i have this:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/
provider/BouncyCastleProvider
        at org.crococryptfile.CrococryptFile.<clinit>(CrococryptFile.java:58)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.Bounc
yCastleProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```
Please any advice to avoid this ?

**Comment by fhissen** [comment]
no bug
